/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("CostEstimationLinesObjectPageObjectPage journey");

        opaTest("Navigate to CostEstimationLinesObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();

            When.onTheMaintenanceNotificationsList.onFilterBar().iExecuteSearch();

            Then.onTheMaintenanceNotificationsList.onTable().iCheckRows();
            When.onTheMaintenanceNotificationsList.onTable().iPressRow(0);

            Then.onTheMaintenanceNotificationsObjectPage.iSeeThisPage();
            Then.onTheMaintenanceNotificationsObjectPage.onTable({ property: "costLines" }).iCheckRows();
            When.onTheMaintenanceNotificationsObjectPage.onTable({ property: "costLines" }).iPressRow(0);

            Then.onTheCostEstimationLinesObjectPage.iSeeThisPage();
        });


        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheCostEstimationLinesObjectPage.iCheckSection({ section: "Main" });
            Then.onTheCostEstimationLinesObjectPage.onForm({ section: "Main" }).iCheckField({ property: "lineNumber" });
            Then.onTheCostEstimationLinesObjectPage.onForm({ section: "Main" }).iCheckField({ property: "costCategory" });
            Then.onTheCostEstimationLinesObjectPage.onForm({ section: "Main" }).iCheckField({ property: "itemDescription" });
            Then.onTheCostEstimationLinesObjectPage.onForm({ section: "Main" }).iCheckField({ property: "quantity" });
            Then.onTheCostEstimationLinesObjectPage.onForm({ section: "Main" }).iCheckField({ property: "unitRate" });
            Then.onTheCostEstimationLinesObjectPage.onForm({ section: "Main" }).iCheckField({ property: "lineAmount" });
            Then.onTheCostEstimationLinesObjectPage.onForm({ section: "Main" }).iCheckField({ property: "currency" });
            Then.onTheCostEstimationLinesObjectPage.onForm({ section: "Main" }).iCheckField({ property: "costCenter" });
            Then.onTheCostEstimationLinesObjectPage.onForm({ section: "Main" }).iCheckField({ property: "createdAt" });
            Then.onTheCostEstimationLinesObjectPage.onForm({ section: "Main" }).iCheckField({ property: "createdBy" });
            Then.onTheCostEstimationLinesObjectPage.onForm({ section: "Main" }).iCheckField({ property: "modifiedAt" });
            Then.onTheCostEstimationLinesObjectPage.onForm({ section: "Main" }).iCheckField({ property: "modifiedBy" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});