/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("MaintenanceNotificationsObjectPageObjectPage journey");

        opaTest("Navigate to MaintenanceNotificationsObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();

            When.onTheMaintenanceNotificationsList.onFilterBar().iExecuteSearch();

            Then.onTheMaintenanceNotificationsList.onTable().iCheckRows();
            When.onTheMaintenanceNotificationsList.onTable().iPressRow(0);

            Then.onTheMaintenanceNotificationsObjectPage.iSeeThisPage();
        });


        opaTest("Check body sections of the Object Page", function (Given, When, Then) {
            Then.onTheMaintenanceNotificationsObjectPage.iCheckNumberOfSections(2);
            When.onTheMaintenanceNotificationsObjectPage.iPressSectionIconTabFilterButton("Main");
            Then.onTheMaintenanceNotificationsObjectPage.iCheckSection({ section: "Main" });
            Then.onTheMaintenanceNotificationsObjectPage.onForm({ section: "Main" }).iCheckField({ property: "notificationNumber" });
            Then.onTheMaintenanceNotificationsObjectPage.onForm({ section: "Main" }).iCheckField({ property: "notificationType" });
            Then.onTheMaintenanceNotificationsObjectPage.onForm({ section: "Main" }).iCheckField({ property: "notificationText" });
            Then.onTheMaintenanceNotificationsObjectPage.onForm({ section: "Main" }).iCheckField({ property: "notifPriority" });
            Then.onTheMaintenanceNotificationsObjectPage.onForm({ section: "Main" }).iCheckField({ property: "notificationStatus" });
            Then.onTheMaintenanceNotificationsObjectPage.onForm({ section: "Main" }).iCheckField({ property: "breakdownIndicator" });
            Then.onTheMaintenanceNotificationsObjectPage.onForm({ section: "Main" }).iCheckField({ property: "reportedByUser" });
            Then.onTheMaintenanceNotificationsObjectPage.onForm({ section: "Main" }).iCheckField({ property: "reportedOnDate" });
            Then.onTheMaintenanceNotificationsObjectPage.onForm({ section: "Main" }).iCheckField({ property: "createdAt" });
            Then.onTheMaintenanceNotificationsObjectPage.onForm({ section: "Main" }).iCheckField({ property: "createdBy" });
            Then.onTheMaintenanceNotificationsObjectPage.onForm({ section: "Main" }).iCheckField({ property: "modifiedAt" });
            Then.onTheMaintenanceNotificationsObjectPage.onForm({ section: "Main" }).iCheckField({ property: "modifiedBy" });
            Then.onTheMaintenanceNotificationsObjectPage.onForm({ section: "Main" }).iCheckField({ property: "functionalLocation_ID" });
            Then.onTheMaintenanceNotificationsObjectPage.onForm({ section: "Main" }).iCheckField({ property: "workCenter_ID" });
            Then.onTheMaintenanceNotificationsObjectPage.onForm({ section: "Main" }).iCheckField({ property: "maintenanceOrder_ID" });
            When.onTheMaintenanceNotificationsObjectPage.iPressSectionIconTabFilterButton("CostEstimationLines");
            Then.onTheMaintenanceNotificationsObjectPage.iCheckSection({ section: "CostEstimationLines" });
       });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});