/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("MaintenanceNotificationsListListReport journey");

        opaTest("Start application", function (Given, When, Then) {
            Given.iStartMyApp();

            Then.onTheMaintenanceNotificationsList.iSeeThisPage();
        });

        opaTest("Check filter bar", function (Given, When, Then) {
            Then.onTheMaintenanceNotificationsList.onFilterBar().iCheckFilterField("Equipment");
            Then.onTheMaintenanceNotificationsList.onFilterBar().iCheckFilterField("Functional Location");
            Then.onTheMaintenanceNotificationsList.onFilterBar().iCheckFilterField("Work Center");
            Then.onTheMaintenanceNotificationsList.onFilterBar().iCheckFilterField("Maintenance Order");
        });

        opaTest("Check table columns and actions", function (Given, When, Then) {
            Then.onTheMaintenanceNotificationsList.onTable().iCheckColumns(undefined, {"notificationNumber":{"header":"Notification Number"},"notificationType":{"header":"Notification Type"},"notificationText":{"header":"Notification Text"},"notifPriority":{"header":"Notification Priority"},"notificationStatus":{"header":"Notification Status"},"breakdownIndicator":{"header":"Breakdown Indicator"},"reportedByUser":{"header":"Reported By User"},"reportedOnDate":{"header":"Reported On Date"},"functionalLocation_ID":{"header":"Functional Location"},"workCenter_ID":{"header":"Work Center"},"maintenanceOrder_ID":{"header":"Maintenance Order"}});

        });



        opaTest("Navigate to ObjectPage", function (Given, When, Then) {
            // Note: this test will fail if the ListReport page doesn't show any data
            
            When.onTheMaintenanceNotificationsList.onFilterBar().iExecuteSearch();
            
            Then.onTheMaintenanceNotificationsList.onTable().iCheckRows();

            When.onTheMaintenanceNotificationsList.onTable().iPressRow(0);
            Then.onTheMaintenanceNotificationsObjectPage.iSeeThisPage();

        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});