/**
 * Code is auto-generated by Application Logic, DO NOT EDIT.
 * @version(2.0)
 */
const LCAPApplicationService = require('@sap/low-code-event-handler');
const before_Maintenancenotifications_Create_Update = require('./code/before-maintenancenotifications-create-update');
const after_Maintenanceorders_Read = require('./code/after-maintenanceorders-read');
const on_Maintenanceorders_Updatecosts = require('./code/on-maintenanceorders-updatecosts');

class my_capmSrv extends LCAPApplicationService {
    async init() {

        this.before(['CREATE', 'UPDATE'], 'MaintenanceNotifications', async (request) => {
            await before_Maintenancenotifications_Create_Update(request);
        });

        this.after('READ', 'MaintenanceOrders', async (results, request) => {
            await after_Maintenanceorders_Read(results, request);
        });

        this.on('updateCosts', 'MaintenanceOrders', async (request) => {
            return on_Maintenanceorders_Updatecosts(request);
        });

        return super.init();
    }
}


module.exports = {
    my_capmSrv
};